[package]
name = "macro-demo-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
am = { version = "0.1.0", package = "my-awesome-macros", path = "../my-awesome-macros" }
